# Generated by Django 5.1.4 on 2025-06-20 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_deliverydriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.deliverydriver'),
        ),
    ]
