# Generated by Django 5.1.4 on 2025-06-24 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assigned_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.deliverydriver'),
        ),
    ]
