# Generated by Django 5.1.4 on 2025-06-25 03:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_deliverydriver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydriver',
            name='current_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverydriver',
            name='profile_picture',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='deliverydriver',
            name='vehicle_plate_number',
            field=models.CharField(max_length=20),
        ),
    ]
