# Generated by Django 5.1.4 on 2025-06-25 04:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_deliverydriver_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydriver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='drivers/'),
        ),
    ]
