# Generated by Django 5.1.4 on 2025-06-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_deliverydriver_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.deliverydriver'),
        ),
    ]
