# Generated by Django 5.1.4 on 2025-06-30 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_store_time_close_store_time_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('date_requested', models.DateField(default=django.utils.timezone.now)),
                ('time_requested', models.TimeField(default=django.utils.timezone.now)),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_remarks', models.TextField(blank=True, null=True)),
                ('driver_comment', models.TextField(blank=True, null=True)),
                ('go_confirmed', models.BooleanField(default=False)),
                ('flat_rate_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.deliverydriver')),
            ],
        ),
    ]
