# Generated by Django 5.1.4 on 2025-06-30 17:39

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_flatrate_specialrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrequest',
            name='date_requested',
            field=models.DateField(default=store.models.default_local_date),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='time_requested',
            field=models.TimeField(default=store.models.default_local_time),
        ),
    ]
