# Generated by Django 5.1.4 on 2025-07-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_specialrequest_date_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrequest',
            name='store',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
