# Generated by Django 5.1.4 on 2025-07-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_specialrequest_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
    ]
