# Generated by Django 5.0.4 on 2025-07-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_specialrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='facebook_page',
        ),
    ]
